/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Jan 29 12:41:03 2018. */

#include "hotspot-data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Hotspot_fields[4] = {
    PB_FIELD(  1, DOUBLE  , SINGULAR, STATIC  , FIRST, Hotspot, latitude, latitude, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, Hotspot, longitude, latitude, 0),
    PB_FIELD(  3, DOUBLE  , SINGULAR, STATIC  , OTHER, Hotspot, temperature, longitude, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
