/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Jan 29 12:40:57 2018. */

#include "header.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Header_fields[3] = {
    PB_FIELD(  1, FIXED32 , SINGULAR, STATIC  , FIRST, Header, message_id, message_id, 0),
    PB_FIELD(  2, FIXED32 , SINGULAR, STATIC  , OTHER, Header, message_length, message_id, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
